all: global local

global:
	../invt2run.py sig5_g.cfg     --c=0.5:0.5:20.0
	../invt2run.py sig5t1e7_g.cfg --c=0.5:0.5:20.0

local:
	../invt2run.py sig5_l.cfg     --c=0.5:0.5:20.0
	../invt2run.py sig5t1e7_l.cfg --c=0.5:0.5:20.0
