all:
	../invt2run.py nb0.24_g.cfg     --c=0.5:0.5:10.0
	../invt2run.py nb0.24_l.cfg     --c=0.5:0.5:10.0
	../invt2run.py nb0.24t1e7_g.cfg --c=0.5:0.5:10.0
	../invt2run.py nb0.24t1e7_l.cfg --c=0.5:0.5:10.0
