all:
	../invt2run.py sig10_g.cfg     --c=0.5:0.5:20.0
	../invt2run.py sig10_l.cfg     --c=0.5:0.5:20.0
	../invt2run.py sig10t1e7_g.cfg --c=0.5:0.5:20.0
	../invt2run.py sig10t1e7_l.cfg --c=0.5:0.5:20.0
